# Generated by Django 5.0.6 on 2024-07-14 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petshopenv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('sku', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagenes_categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('stock', models.IntegerField()),
                ('img', models.ImageField(upload_to='imagenes_producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Petshopenv.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gmail', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MiModelo',
        ),
    ]
