# Generated by Django 4.1 on 2024-07-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petshopenv', '0002_categoria_producto_usuario_delete_mimodelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
